### Create a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "John Doe GG101",
  "email": "johndoeGG1211120@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1995-01-02",
  "registeredDate": "2024-03-03"
}

###